// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxbmbnfpgnkcrjacxegi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4Ym1ibmZwZ25rY3JqYWN4ZWdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2ODY5NzAsImV4cCI6MjA2NzI2Mjk3MH0.UVRKet1pFfFzRm2zz5NAZ9XCADZ0hZBMTApy7TwCFXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});